travis:
  secure:
    BINSTAR_TOKEN: iVX/T0pJ+lBPCwH1S87n9gqoEZhBL1/Ow5l+95bOuAMdWzUwlcH9ocoP5XSwybF/upr8tn9gRRQHkernsJVpU8/GvJJmeohGdNoNBhNxcrHcRBu2Jf62dcNS7b0vpS6qDjCtFGeHdzX64bPyw8wMeC3ljfXzV5ibxGBEt543QPWDxhr+KxG/qBuTFl8FIA7Dq0iJSDppNyQEmeWGkBUzXdZFaqyghwtLPd5VA7r2VIOFRNNJKcxcQM/f2fbIgX9C6AB6/UBlmSucOw8Rh/VECbk8uWcNBW02LpuT9ox4eF5bA/FWBuhT9+/q1OipaBjqUdae3Zm+z5CYd6QIP6Xedfk1sxfPXPUov+D/Y8CCxwOq0kiECeqhg5jZpfKkvvsZBCb7AUtkC7hxBG+3Q8PbiCytwA3NXLR2icybXMOtsIRmWmhoKk2QeQJ6ZrDhKhZ6O0bDkPNapqHNdgKPGF6EOuMMgfF2yLzFjf9W+UEP4cDaMdkhes+m/RiEEq7Iy/w87n1zA0r/blvjNEx3lGFaGAG3MP2fDFZFXB7I4p3XukrltrPfz7VwX6NVdvAXTLMBIIPLMCdxD29kG4/AKp8hay9Isij7o8UmzDxOZQr9ff6/ixe81b+sHAWeQt+oVXVnXV9oKupzOdLxmkY58/2uAnGIHUjJO0rbAABXyuOqVQs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
